In [1]:
import fasttext
import numpy as np
import pandas as pd

In [20]:
model = fasttext.load_model('cc.id.300.bin')

In [2]:
df = pd.read_json('datalabels_inset_3.json')
df

text             author  \
0     Turunkan tunjangan untuk DPR, alihkan untuk su...  abu studio chanel   
1     Terimakasih pak de Saya seorang tukang ojek ka...           al rozaq   
2     Saya sebagai rakyat kecil mendengar bbm naik s...        Davin Davin   
3     Terima kasih banyak Pak Jokowi. Kebijakan Bapa...          Zul Haqqi   
4     Semoga Allah SWT memudahkan semua urusan rakya...      R.E. Handhita   
...                                                 ...                ...   
2995  Pupuk subsidi langka,,, \nBBM naik,,, \nHarga ...       Heru Purnomo   
2996  Saya berharap bbm turun. Kasihan anak kost di ...         Nerry_shop   
2997  saran saya daripada ngasih BLT yg tidak merata...       jubez gaming   
2998                        Presiden blusukan mantapp 😂          dea bagas   
2999  Dari dulu hingga skarang sama harga bukn turun...            Jono no   

                                              cleantext  \
0     turunkan tunjangan untuk dpr alihkan untuk sub...   
1     terimakasih pak de saya seorang tukang ojek ka...   
2     saya sebagai rakyat kecil mendengar bbm naik s...   
3     terima kasih banyak pak jokowi kebijakan bapak...   
4     semoga allah swt memudahkan semua urusan rakya...   
...                                                 ...   
2995  pupuk subsidi langka bbm naik harga gabah dan ...   
2996  saya berharap bbm turun kasihan anak kost di p...   
2997  saran saya daripada ngasih blt yg tidak merata...   
2998                          presiden blusukan mantapp   
2999  dari dulu hingga skarang sama harga bukn turun...   

                                              tokenized  \
0     [turunkan, tunjangan, untuk, dpr, alihkan, unt...   
1     [terimakasih, pak, de, saya, seorang, tukang, ...   
2     [saya, sebagai, rakyat, kecil, mendengar, bbm,...   
3     [terima, kasih, banyak, pak, jokowi, kebijakan...   
4     [semoga, allah, swt, memudahkan, semua, urusan...   
...                                                 ...   
2995  [pupuk, subsidi, langka, bbm, naik, harga, gab...   
2996  [saya, berharap, bbm, turun, kasihan, anak, ko...   
2997  [saran, saya, daripada, ngasih, blt, yg, tidak...   
2998                      [presiden, blusukan, mantapp]   
2999  [dari, dulu, hingga, skarang, sama, harga, buk...   

                                               stemming  polarity   labels  
0     [turun, tunjang, untuk, dpr, alih, untuk, subs...   -0.0024  negatif  
1     [terimakasih, pak, de, saya, orang, tukang, oj...   -0.0013  negatif  
2     [saya, bagai, rakyat, kecil, dengar, bbm, naik...   -0.0067  negatif  
3     [terima, kasih, banyak, pak, jokowi, bijak, ba...    0.0090  positif  
4     [moga, allah, swt, mudah, semua, urus, rakyat,...    0.1049  positif  
...                                                 ...       ...      ...  
2995  [pupuk, subsidi, langka, bbm, naik, harga, gab...   -0.2002  negatif  
2996  [saya, harap, bbm, turun, kasihan, anak, kost,...   -0.0557  negatif  
2997  [saran, saya, daripada, ngasih, blt, yg, tidak...   -0.0042  negatif  
2998                      [presiden, blusukan, mantapp]    0.6124  positif  
2999  [dari, dulu, hingga, skarang, sama, harga, buk...    0.0233  positif  

[3000 rows x 7 columns]

In [3]:
df.dtypes

text          object
author        object
cleantext     object
tokenized     object
stemming      object
polarity     float64
labels        object
dtype: object

In [16]:
df['cleantext'].to_csv('cleantext.txt')

In [3]:
model = fasttext.train_unsupervised('cleantext.txt', minn=2, maxn=6, dim=300)

In [4]:
coba = model.get_sentence_vector('saya sayang kamu')

In [4]:
arr = []
for i in df['stemming']:
    arr.append(model.get_sentence_vector(' '.join(i)))

In [5]:
arr = np.array(arr)

In [6]:
from sklearn.preprocessing import LabelEncoder
labenc = LabelEncoder()
label = df['labels'].values
y = labenc.fit_transform(label)
y

array([0, 0, 0, ..., 0, 1, 1])

In [7]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(arr,y,test_size = 0.25,random_state=0)

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
clf = GaussianNB()
clf.fit(xtrain, ytrain)

GaussianNB()

In [10]:
ypred=clf.predict(xtest)

In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print("Nilai Akurasi : ",accuracy_score(ytest,ypred))
print(classification_report(ytest,ypred))

Nilai Akurasi :  0.5573333333333333
              precision    recall  f1-score   support

           0       0.56      0.95      0.71       419
           1       0.49      0.06      0.11       331

    accuracy                           0.56       750
   macro avg       0.52      0.51      0.41       750
weighted avg       0.53      0.56      0.44       750



In [27]:
ypred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [30]:
hasil = [coba]
clf.predict(hasil)

array([0])